---
# Configuration of postgresql server

- name: Installing PostgreSQL server
  pacman: name={{item}} state=present
  with_items:
    - postgresql
    - python2-psycopg2

- name: Create tmpfiles.d file for /run/postgresql
  command: systemd-tmpfiles --create postgresql.conf

- name: Create PostgreSQL data directory
  file: dest=/var/lib/postgres/data owner=postgres group=postgres mode=0700 state=directory

- name: Initializing database
  sudo_user: postgres
  shell: /usr/bin/initdb -D '/var/lib/postgres/data' creates=/var/lib/postgres/data/pg_hba.conf

- name: Starting PostgreSQL
  command: systemctl start postgresql

- name: Configuring a 'devel' user
  sudo_user: postgres
  postgresql_user: user=devel password=123456 state=present

- name: Starting PostgreSQL on boot
  command: systemctl enable postgresql

- name: Restarting Postgresql service
  command: systemctl restart postgresql

- name: Removing temporary packages
  pacman: name=python2-psycopg2 state=absent

