---
# Development configuration

- name: Installing Version Control Systems
  sudo: yes
  apt: pkg=git,mercurial,gitg,meld state=installed

- name: Configuring GIT defaults
  template: src=common/templates/.gitconfig.j2 dest=/home/${username}/.gitconfig owner=$username group=$username mode=0644 backup=yes

- name: Configuring VIM defaults
  copy: src=common/files/.exrc dest=/home/${username}/.exrc owner=$username group=$username mode=0644 backup=yes

- name: Checking Heroku toolbelt installation
  sudo: yes
  register: inst_heroku
  file: path=/usr/local/heroku state=directory

- name: Installing Ubuntu Heroku toolbelt
  sudo: yes
  shell: wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  when_changed: $inst_heroku

- name: Checking Pythonz installation
  register: inst_pythonz
  file: path=/home/${username}/.pythonz state=directory

- name: Installing Pythonz
  shell: curl -kL https://raw.github.com/saghul/pythonz/master/pythonz-install | bash
  when_changed: $inst_pythonz

- name: Installing PIP
  apt: pkg=python-pip state=installed

- name: Checking Python virtualenvwrapper installation
  sudo: yes
  register: inst_virtualenvwrapper
  file: path=/usr/local/bin/virtualenvwrapper.sh

- name: Installing Python virtualenv
  sudo: yes
  shell: pip install virtualenvwrapper
  when_changed: $inst_virtualenvwrapper

- name: Installing system Ruby
  sudo: yes
  apt: pkg=ruby state=latest

- name: Checking Ruby RVM installation
  register: inst_rvm
  file: path=/home/${username}/.rvm state=directory

- name: Installing Ruby RVM
  shell: \curl -L https://get.rvm.io | bash -s stable
  when_changed: $inst_rvm

- name: Checking Oracle JDK 7 installation
  sudo: yes
  register: inst_java
  file: path=/usr/lib/jvm/java-7-oracle state=directory

- name: Enabling Oracle JDK 7 PPA
  sudo: yes
  apt_repository: repo=ppa:webupd8team/java
  when_changed: $inst_java

- name: Unattended installation
  sudo: yes
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

- name: Installing Oracle JDK 7
  sudo: yes
  apt: pkg=oracle-java7-installer state=latest update_cache=yes
  when_changed: $inst_java

- name: Installing Maven
  sudo: yes
  apt: pkg=maven state=installed

- name: Installing Ant
  sudo: yes
  apt: pkg=ant state=installed

- name: Installing Node Version Manager (NVM)
  register: inst_nvm
  git: repo=git://github.com/creationix/nvm.git dest=/home/${username}/.nvm

- name: Checking Seam Framework installation
  register: inst_seam
  file: path=/home/${username}/program/jboss-seam-2.3.0.Final state=directory

- name: Downloading Seam Framework
  get_url: url=$seam dest=/tmp/seam.tar.gz
  when_changed: $inst_seam

- name: Installing Seam Framework
  command: tar -xzf /tmp/seam.tar.gz -C /home/${username}/program/
  when_changed: $inst_seam